version: '3.7'
services:
  api:
    container_name: mfa_chatbot_api
    restart: always
    build: .
    ports:
     - ${EXTERNAL_PORT:-5322}:${INTERNAL_PORT:-5000}
    volumes:
     - .:/code
    environment:
      - PORT=${INTERNAL_PORT:-5000}
      - TZ=${TZ:-America/Mazatlan}
      - DEV_MODE=${DEV_MODE}
      - BASE_URL=${BASE_URL}
